### ISSUE TITLE
Use jinja2 for loop

### ISSUE THREAD

**Issue by thystips** [jlu5/ansible-dn42#24]
https://github.com/jlu5/ansible-dn42/blob/ae48479ff19f1b6888737b249f5db91a86236f5a/roles/config-bird2/config/community_filters.conf#L138

Great job with your config !

For answer to "Prepend 3x to a peer on export. Wouldn't native loops in bird config be great?", native loops isn't possible but with Ansible and Jinja2 it can be a solution to write less conf ? ;-)

**Comment by jlu5** [comment]
I mean sure, that's an option. But the drawback of templating out large sections of config code is that it hurts readability quite significantly. In that regard, I'm not so sure the benefit outweighs the cost here.
